**1.1 Set host name cho server

hostnamectl set-hostname mail.trungtm.tech ( sửa lại tên svr mail của bạn)

**1.2 Disable Selinux

vi /etc/selinux/config

This file controls the state of SELinux on the system.
SELINUX= can take one of these three values:
enforcing - SELinux security policy is enforced.
permissive - SELinux prints warnings instead of enforcing.
disabled - No SELinux policy is loaded.

SELINUX=disabled
SELINUXTYPE= can take one of three values:
targeted - Targeted processes are protected,
minimum - Modification of targeted policy. Only selected processes are protected.
mls - Multi Level Security protection.
SELINUXTYPE=targeted

**Reboot server sau khi disabled Selinux

**1.3 UPDATE OS

yum update reboot

**1.4 CẤU HÌNH NETWORK & DNS

**Cài đặt phần mềm DNS Master Server

yum install bind bind-utils -y

**Sửa file hosts

vi /etc/hosts

127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4 ::1 localhost localhost.localdomain localhost6 localhost6.localdomain6

10.0.210.19 mail.trungtm.tech mail //IP cua server mail

**Sửa file named.conf

vi /etc/named.conf

// // named.conf // // Provided by Red Hat bind package to configure the ISC BIND named(8) DNS // server as a caching only nameserver (as a localhost DNS resolver only). // // See /usr/share/doc/bind*/sample/ for example named configuration files. // // See the BIND Administrator's Reference Manual (ARM) for details about the // configuration located in /usr/share/doc/bind-{version}/Bv9ARM.html

options { listen-on port 53 { 127.0.0.1;}; listen-on-v6 port 53 { ::1; }; directory "/var/named"; dump-file "/var/named/data/cache_dump.db"; statistics-file "/var/named/data/named_stats.txt"; memstatistics-file "/var/named/data/named_mem_stats.txt"; recursing-file "/var/named/data/named.recursing"; secroots-file "/var/named/data/named.secroots"; allow-query { localhost; }; allow-query-cache { localhost; };

	forwarders {
   	8.8.8.8;
   	8.8.4.4;
	};

	/*
 	- If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
 	- If you are building a RECURSIVE (caching) DNS server, you need to enable
   	recursion.
 	- If your recursive DNS server has a public IP address, you MUST enable access
   	control to limit queries to your legitimate users. Failing to do so will
   	cause your server to become part of large scale DNS amplification
   	attacks. Implementing BCP38 within your network would greatly
   	reduce such attack surface
	*/
	recursion yes;

          dnssec-enable yes;
	dnssec-validation yes;

	/* Path to ISC DLV key */
	bindkeys-file "/etc/named.root.key";

	managed-keys-directory "/var/named/dynamic";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";

};

logging { channel default_debug { file "data/named.run"; severity dynamic; }; };

zone "." IN { type hint; file "named.ca"; };

zone "trungtm.tech" IN { type master; file "trungtm.tech"; notify yes; };

include "/etc/named.rfc1912.zones"; include "/etc/named.root.key";

**Tạo zone thuận

vi /var/named/trungtm.tech

$TTL 86400
@ IN SOA @ mail.trungtm.tech (
42                 ; Serial
3H                ; Refresh
15M              ; Retry
1W                ; Expire
1D                 ; Minimum
)
@                  IN NS        mail.trungtm.tech.
trungtm.tech.   MX 10 mail.trungtm.tech.
mail              IN A          10.0.210.19


**Cấp quyền và start, enable dịch vụ

chgrp named -R /var/named
chown -v root:named /etc/named.conf
restorecon -rv /var/named
restorecon /etc/named.conf
systemctl enable named
systemctl start named


**Kiểm tra cú pháp của các file DNS

named-checkconf /etc/named.conf

Output không hiện ra gì nghĩa là file named.conf đã cấu hình chuẩn

named-checkzone trungtm.tech /var/named/trungtm.tech

Output

zone trungtm.tech/IN: loaded serial 42
OK

**Trỏ DNS về mình

vi /etc/sysconfig/network-scripts/ifcfg-ens192

TYPE=Ethernet 
PROXY_METHOD=none 
BROWSER_ONLY=no BOOTPROTO=none
DEFROUTE=yes 
IPV4_FAILURE_FATAL=yes 
IPV6INIT=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes 
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens192 
UUID=f1dd2db2-81ba-444d-80ef-c2b2b98d6d0e 
DEVICE=ens192 
ONBOOT=yes 
IPADDR=10.0.210.19
PREFIX=24 
GATEWAY=10.0.210.1 
DNS1=127.0.0.1 
IPV6_PRIVACY=no 
DOMAIN=trungtm.tech

**Sau đó khởi động lại mạng:

systemctl restart network

**Kiểm tra:

cat /etc/resolv.conf

Output
Generated by NetworkManager

search trungtm.tech nameserver 10.0.210.19

**Kiểm tra kết nối internet:

ping -c 3 google.com.vn

**Enable EPEL Repos cho Redhat 7.x:

wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

**Nếu không chạy được hãy chạy lệnh cài wget : yum install wget -y**

**Enable “ELREPO” cho Redhat 7.x

rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org 
rpm -Uvh http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

**Cài đặt các gói phụ trợ cần thiết

yum install epel-release -y 
yum install vim rsync htop telnet strace iotop screen htop wget net-tools lsof vim-enhanced nmap unzip sudo sysstat perl-core route bind-utils git -y

**Thiết lập Firewall (stop và disable)

systemctl stop firewall 
systemctl disable firewalld

**Kiểm tra các bản ghi DNS Bước 1: Kiểm tra bản ghi DNS MX

dig mx trungtm.tech (Your domain)

Output


; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.13 <<>> mx trungtm.tech
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56281
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;trungtm.tech.                  IN      MX

;; ANSWER SECTION:
trungtm.tech.           86400   IN      MX      10 mail.trungtm.tech.

;; AUTHORITY SECTION:
trungtm.tech.           86400   IN      NS      mail.trungtm.tech.

;; ADDITIONAL SECTION:
mail.trungtm.tech.      86400   IN      A       10.0.210.19

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Jun 12 10:43:16 +07 2023
;; MSG SIZE  rcvd: 92

**Kiểm tra và stop các dịch vụ xung đột với zimbra

systemctl disable postfix
systemctl stop postfix

*Tải file cài đặt zimbra

wget https://files.zimbra.com/downloads/8.8.15_GA/zcs-8.8.15_GA_3869.RHEL7_64.20190918004220.tgz --no-check-certificate

tar -xvzf zcs-8.8.15_GA_3869.RHEL7_64.20190918004220.tgz

cd zzcs-8.8.15_GA_3869.RHEL7_64.20190918004220.tgz

./install.sh

Operations logged to /tmp/install.log.4qxELesC
Checking for existing installation...
    zimbra-drive...NOT FOUND
    zimbra-imapd...NOT FOUND
    zimbra-patch...NOT FOUND
    zimbra-license-tools...NOT FOUND
    zimbra-license-extension...NOT FOUND
    zimbra-network-store...NOT FOUND
    zimbra-network-modules-ng...NOT FOUND
    zimbra-chat...NOT FOUND
    zimbra-talk...NOT FOUND
    zimbra-ldap...NOT FOUND
    zimbra-logger...NOT FOUND
    zimbra-mta...NOT FOUND
    zimbra-dnscache...NOT FOUND
    zimbra-snmp...NOT FOUND
    zimbra-store...NOT FOUND
    zimbra-apache...NOT FOUND
    zimbra-spell...NOT FOUND
    zimbra-convertd...NOT FOUND
    zimbra-memcached...NOT FOUND
    zimbra-proxy...NOT FOUND
    zimbra-archiving...NOT FOUND
    zimbra-core...NOT FOUND


----------------------------------------------------------------------
PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THE SOFTWARE.
SYNACOR, INC. ("SYNACOR") WILL ONLY LICENSE THIS SOFTWARE TO YOU IF YOU
FIRST ACCEPT THE TERMS OF THIS AGREEMENT. BY DOWNLOADING OR INSTALLING
THE SOFTWARE, OR USING THE PRODUCT, YOU ARE CONSENTING TO BE BOUND BY
THIS AGREEMENT. IF YOU DO NOT AGREE TO ALL OF THE TERMS OF THIS
AGREEMENT, THEN DO NOT DOWNLOAD, INSTALL OR USE THE PRODUCT.

License Terms for this Zimbra Collaboration Suite Software:
https://www.zimbra.com/license/zimbra-public-eula-2-6.html
----------------------------------------------------------------------



Do you agree with the terms of the software license agreement? [N] Y (Chọn Y/Yes)

Do you agree with the terms of the software license agreement? [N] Y (Chọn Y/Yes)

Use Zimbra's package repository [Y] //Nhấn enter

Importing Zimbra GPG key

Configuring package repository

Checking for installable packages

Found zimbra-core (local) 
Found zimbra-ldap (local) 
Found zimbra-logger (local) 
Found zimbra-mta (local) 
Found zimbra-dnscache (local)
Found zimbra-snmp (local) 
Found zimbra-store (local) 
Found zimbra-apache (local)
Found zimbra-spell (local) 
Found zimbra-memcached (repo) 
Found zimbra-proxy (local) 
Found zimbra-drive (repo) 
Found zimbra-imapd (local) 
Found zimbra-patch (repo)

Select the packages to install

Install zimbra-ldap [Y]

Install zimbra-logger [Y]

Install zimbra-mta [Y]

Install zimbra-dnscache [Y] N

Install zimbra-snmp [Y]

Install zimbra-store [Y]

Install zimbra-apache [Y]

Install zimbra-spell [Y]

Install zimbra-memcached [Y]

Install zimbra-proxy [Y]

Install zimbra-drive [Y] N

Install zimbra-imapd (BETA - for evaluation only) [N]

Install zimbra-chat [Y] N 
Checking required space for zimbra-core 
Checking space for zimbra-store 
Checking required packages for zimbra-store 
zimbra-store package check complete.

Installing:
zimbra-core 
zimbra-ldap 
zimbra-logger 
zimbra-mta 
zimbra-snmp 
zimbra-store 
zimbra-apache 
zimbra-spell 
zimbra-memcached 
zimbra-proxy 
zimbra-patch

The system will be modified. Continue? [N] Y

Beginning Installation - see /tmp/install.log.4qxELesC for details...

                      zimbra-core-components will be downloaded and installed.
                        zimbra-timezone-data will be installed.
                      zimbra-common-core-jar will be installed.
                     zimbra-common-mbox-conf will be installed.
               zimbra-common-mbox-conf-attrs will be installed.
                zimbra-common-mbox-conf-msgs will be installed.
              zimbra-common-mbox-conf-rights will be installed.
                       zimbra-common-mbox-db will be installed.
                     zimbra-common-mbox-docs will be installed.
               zimbra-common-mbox-native-lib will be installed.
                     zimbra-common-core-libs will be installed.
                                 zimbra-core will be installed.
                      zimbra-ldap-components will be downloaded and installed.
                                 zimbra-ldap will be installed.
                               zimbra-logger will be installed.
                       zimbra-mta-components will be downloaded and installed.
                                  zimbra-mta will be installed.
                      zimbra-snmp-components will be downloaded and installed.
                                 zimbra-snmp will be installed.
                     zimbra-store-components will be downloaded and installed.
                   zimbra-jetty-distribution will be downloaded and installed.
                            zimbra-mbox-conf will be installed.
                             zimbra-mbox-war will be installed.
                         zimbra-mbox-service will be installed.
                   zimbra-mbox-webclient-war will be installed.
               zimbra-mbox-admin-console-war will be installed.
                      zimbra-mbox-store-libs will be installed.
                                zimbra-store will be installed.
                    zimbra-apache-components will be downloaded and installed.
                               zimbra-apache will be installed.
                     zimbra-spell-components will be downloaded and installed.
                                zimbra-spell will be installed.
                            zimbra-memcached will be downloaded and installed.
                     zimbra-proxy-components will be downloaded and installed.
                                zimbra-proxy will be installed.
                                zimbra-patch will be downloaded and installed (later).


Downloading packages (10):
   zimbra-core-components
   zimbra-ldap-components
   zimbra-mta-components
   zimbra-snmp-components
   zimbra-store-components
   zimbra-jetty-distribution
   zimbra-apache-components
   zimbra-spell-components
   zimbra-memcached
   zimbra-proxy-components
    ...done

Installing local packages (25):
   zimbra-timezone-data
   zimbra-common-core-jar
   zimbra-common-mbox-conf
   zimbra-common-mbox-conf-attrs
   zimbra-common-mbox-conf-msgs
   zimbra-common-mbox-conf-rights
   zimbra-common-mbox-db
   zimbra-common-mbox-docs
   zimbra-common-mbox-native-lib
   zimbra-common-core-libs
   zimbra-core
   zimbra-ldap
   zimbra-logger
   zimbra-mta
   zimbra-snmp
   zimbra-mbox-conf
   zimbra-mbox-war
   zimbra-mbox-service
   zimbra-mbox-webclient-war
   zimbra-mbox-admin-console-war
   zimbra-mbox-store-libs
   zimbra-store
   zimbra-apache
   zimbra-spell
   zimbra-proxy
   ...done
Installing extra packages (1): zimbra-patch ...done

Running Post Installation Configuration: 
Operations logged to /tmp/zmsetup.20230203-084439.log 
Installing LDAP configuration database...done. 
Setting defaults...

DNS ERROR resolving MX for mail.trungtm.tech 
It is suggested that the domain name have an MX record configured in DNS 
Change domain name? [Yes] yes Create domain: [mail.trungtm.tech] trungtm.tech 
	MX: mail.trungtm.tech (10.0.210.19)

    Interface: 127.0.0.1
    Interface: ::1
    Interface: 10.0.210.19

done. 
Checking for port conflicts

Main menu

1) Common Configuration:
   2) zimbra-ldap:                             Enabled
   3) zimbra-logger:                           Enabled
   4) zimbra-mta:                              Enabled
   5) zimbra-snmp:                             Enabled
   6) zimbra-store:                            Enabled
        +Create Admin User:                    yes
        +Admin user to create:                 admin@trungtm.tech
******* +Admin Password                        UNSET
        +Anti-virus quarantine user:           virus-quarantine.7wze8im0r@trungtm.tech
        +Enable automated spam training:       yes
        +Spam training user:                   spam.9i_g27koi6@trungtm.tech
        +Non-spam(Ham) training user:          ham.kfsuz6gw@trungtm.tech
        +SMTP host:                            mail.trungtm.tech
        +Web server HTTP port:                 8080
        +Web server HTTPS port:                8443
        +Web server mode:                      https
        +IMAP server port:                     7143
        +IMAP server SSL port:                 7993
        +POP server port:                      7110
        +POP server SSL port:                  7995
        +Use spell check server:               yes
        +Spell server URL:                     http://mail.trungtm.tech:7780/aspell.php
        +Enable version update checks:         TRUE
        +Enable version update notifications:  TRUE
        +Version update notification email:    admin@trungtm.tech
        +Version update source email:          admin@trungtm.tech
        +Install mailstore (service webapp):   yes
        +Install UI (zimbra,zimbraAdmin webapps): yes

   7) zimbra-spell:                            Enabled
   8) zimbra-proxy:                            Enabled
   9) Default Class of Service Configuration:
   s) Save config to file
   x) Expand menu
   q) Quit

Address unconfigured (**) items  (? - help) 6

Store configuration

   1) Status:                                  Enabled
   2) Create Admin User:                       yes
   3) Admin user to create:                    admin@trungtm.tech
** 4) Admin Password                           UNSET
   5) Anti-virus quarantine user:              virus-quarantine.7wze8im0r@trungtm.tech
   6) Enable automated spam training:          yes
   7) Spam training user:                      spam.9i_g27koi6@trungtm.tech
   8) Non-spam(Ham) training user:             ham.kfsuz6gw@trungtm.tech
   9) SMTP host:                               mail.trungtm.tech
  10) Web server HTTP port:                    8080
  11) Web server HTTPS port:                   8443
  12) Web server mode:                         https
  13) IMAP server port:                        7143
  14) IMAP server SSL port:                    7993
  15) POP server port:                         7110
  16) POP server SSL port:                     7995
  17) Use spell check server:                  yes
  18) Spell server URL:                        http://mail.trungtm.tech:7780/aspell.php
  19) Enable version update checks:            TRUE
  20) Enable version update notifications:     TRUE
  21) Version update notification email:       admin@trungtm.tech
  22) Version update source email:             admin@trungtm.tech
  23) Install mailstore (service webapp):      yes
  24) Install UI (zimbra,zimbraAdmin webapps): yes

Select, or 'r' for previous menu [r] 4

Password for admin@trungtm.tech (min 6 characters): [w1WXcxU3] "Your password"

Store configuration

   1) Status:                                  Enabled
   2) Create Admin User:                       yes
   3) Admin user to create:                    admin@trungtm.tech
   4) Admin Password                           set
   5) Anti-virus quarantine user:              virus-quarantine.7wze8im0r@trungtm.tech
   6) Enable automated spam training:          yes
   7) Spam training user:                      spam.9i_g27koi6@trungtm.tech
   8) Non-spam(Ham) training user:             ham.kfsuz6gw@trungtm.tech
   9) SMTP host:                               mail.trungtm.tech
  10) Web server HTTP port:                    8080
  11) Web server HTTPS port:                   8443
  12) Web server mode:                         https
  13) IMAP server port:                        7143
  14) IMAP server SSL port:                    7993
  15) POP server port:                         7110
  16) POP server SSL port:                     7995
  17) Use spell check server:                  yes
  18) Spell server URL:                        http://mail.trungtm.tech:7780/aspell.php
  19) Enable version update checks:            TRUE
  20) Enable version update notifications:     TRUE
  21) Version update notification email:       admin@trungtm.tech
  22) Version update source email:             admin@trungtm.tech
  23) Install mailstore (service webapp):      yes
  24) Install UI (zimbra,zimbraAdmin webapps): yes

Select, or 'r' for previous menu [r] r //Press R

Main menu

   1) Common Configuration:
   2) zimbra-ldap:                             Enabled
   3) zimbra-logger:                           Enabled
   4) zimbra-mta:                              Enabled
   5) zimbra-snmp:                             Enabled
   6) zimbra-store:                            Enabled
   7) zimbra-spell:                            Enabled
   8) zimbra-proxy:                            Enabled
   9) Default Class of Service Configuration:
   s) Save config to file
   x) Expand menu
   q) Quit

*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help) a //Press a
Save configuration data to a file? [Yes] Y
Save config in file: [/opt/zimbra/config.7288]
Saving config in /opt/zimbra/config.7288...done.
The system will be modified - continue? [No] Y

Operations logged to /tmp/zmsetup.20230203-084439.log
Setting local config values...done.
Initializing core config...Setting up CA...done.
Deploying CA to /opt/zimbra/conf/ca ...done.
Creating SSL zimbra-store certificate...done.
Creating new zimbra-ldap SSL certificate...done.
Creating new zimbra-mta SSL certificate...done.
Creating new zimbra-proxy SSL certificate...done.
Installing mailboxd SSL certificates...done.
Installing MTA SSL certificates...done.
Installing LDAP SSL certificate...done.
Installing Proxy SSL certificate...done.
Initializing ldap...done.
Setting replication password...done.
Setting Postfix password...done.
Setting amavis password...done.
Setting nginx password...done.
Setting BES searcher password...done.
Creating server entry for mail.trungtm.tech...done.
Setting Zimbra IP Mode...done.
Saving CA in ldap...done.
Saving SSL Certificate in ldap...done.
Setting spell check URL...done.
Setting service ports on mail.trungtm.tech...done.
Setting zimbraFeatureTasksEnabled=TRUE...done.
Setting zimbraFeatureBriefcasesEnabled=TRUE...done.
Checking current setting of zimbraReverseProxyAvailableLookupTargets
Querying LDAP for other mailstores
Searching LDAP for reverseProxyLookupTargets...done.
Adding mail.trungtm.tech to zimbraReverseProxyAvailableLookupTargets
Updating zimbraLDAPSchemaVersion to version '1537783098'
Setting TimeZone Preference...done.
Disabling strict server name enforcement on mail.trungtm.tech...done.
Initializing mta config...done.
Setting services on mail.trungtm.tech...done.
Adding mail.trungtm.tech to zimbraMailHostPool in default COS...done.
Creating domain trungtm.tech...done.
Setting default domain name...done.
Creating domain trungtm.tech...already exists.
Creating admin account admin@trungtm.tech...done.
Creating root alias...done.
Creating postmaster alias...done.
Creating user spam.9i_g27koi6@trungtm.tech...done.
Creating user ham.kfsuz6gw@trungtm.tech...done.
Creating user virus-quarantine.7wze8im0r@trungtm.tech...done.
Setting spam training and Anti-virus quarantine accounts...done.
Initializing store sql database...done.
Setting zimbraSmtpHostname for mail.trungtm.tech...done.
Configuring SNMP...done.
Setting up syslog.conf...done.
Starting servers...done.
Installing common zimlets...
        com_zimbra_adminversioncheck...done.
        com_zimbra_attachcontacts...done.
        com_zimbra_attachmail...done.
        com_zimbra_bulkprovision...done.
        com_zimbra_cert_manager...done.
        com_zimbra_clientuploader...done.
        com_zimbra_date...done.
        com_zimbra_email...done.
        com_zimbra_mailarchive...done.
        com_zimbra_phone...done.
        com_zimbra_proxy_config...done.
        com_zimbra_srchhighlighter...done.
        com_zimbra_tooltip...done.
        com_zimbra_url...done.
        com_zimbra_viewmail...done.
        com_zimbra_webex...done.
        com_zimbra_ymemoticons...done.
Finished installing common zimlets.
Restarting mailboxd...done.
Creating galsync account for default domain...done.

You have the option of notifying Zimbra of your installation.
This helps us to track the uptake of the Zimbra Collaboration Server. 
The only information that will be transmitted is: 
	TThe VERSION of zcs installed (8.8.15_GA_3869_RHEL7_64) 
	The ADMIN EMAIL ADDRESS created (admin@trungtm.tech)

Notify Zimbra of your installation? [Yes] Y 
Notifying Zimbra of installation via http://www.zimbra.com/cgi-bin/notify.cgi?VER=8.8.15_GA_3869_RHEL7_64&MAIL=admin@trungtm.tech

ERROR: Notification failed 
Checking if the NG started running...done. 	
Setting up zimbra crontab...done.

Moving /tmp/zmsetup.20230203-084439.log to /opt/zimbra/log

Configuration complete - press return to exit

su zimbra [zimbra@mail]$ zmcontrol -v 
Release 8.8.15_GA_3869.RHEL7_64_20190917004220 RHEL7_64 FOSS edition, Patch 8.8.15_P40.

**Vào Admin Console chỉnh proxy mở port 9071 để khi vào Admin Console thì vào bằng proxy chứ không vào bàng port 7071 của mailbox

    Home -> Configure -> Servers -> mail.trungtm.tech -> Proxy:
    Tại Proxy tich vào Enable admin console proxy,
    tại IMAP clear text login mode chọn both clear text and startls,
    tại POP3 clear text login mode chọn both clear text and startls
Ấn save để lưu

**Mở port cần thiết của Zimbra (Mở port trên Firewall, Modem,... tùy vào thực tế bạn đang sử dụng thiết bị nào) **
Ở đây mình dùng firewall Pfsense : 


1/ Tạo Alias Port: Firewall -> Alisas -> Ports -> Add -> Name: Zimbra -> Type: Ports -> Port : Add tất cả port bên dưới vào -> Save ![image](https://github.com/trungtm97/Zimbra-Mail/assets/134046186/73e6d71e-fb28-4f53-ad93-af604b457455)


2/ Sau đó NAT Alias Port: Firewall -> NAT -> Port Forward -> Add -> ![image](https://github.com/trungtm97/Zimbra-Mail/assets/134046186/9ec8aacf-fc85-413e-ae32-63aae9e80d00)

SMTP        	25	    tcp,
HTTP	        80	    tcp,
POP3	        110 	    tcp,	
IMAP	        143	    tcp, 
LDAP	        389	    tcp,	
HTTPS	        443	    tcp,	
SMTPS	        465	    tcp,	
SMTP Submission	587	    tcp,	
IMAPS	        993	    tcp,	
POP3S	        995	    tcp,	
Admin Itf 	7071	    tcp,	
SOAP Auth	7073        tcp,
LMTP	        7025	    tcp,






















